apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "inventory-platform.fullname" . }}-config
  labels:
    {{- include "inventory-platform.labels" . | nindent 4 }}

data:
  APP_NAME: {{ .Values.config.appName | quote }}
  APP_VERSION: {{ .Values.config.appVersion | quote }}
  DATABASE_NAME: {{ .Values.config.databaseName | quote }}